services:
  app:
    build: .
    container_name: zatech-bot
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      PORT: 4321
    ports:
      - "4321:4321"
    volumes:
      - ./bot.db:/app/bot.db
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: zatech-bot-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zatech_bot
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    restart: unless-stopped

volumes:
  postgres-data:
